// Assemble the GitHub Pages site:
//   gh-pages/
//   ├── index.html   — landing wrapper (banner + iframe of /app/)
//   ├── trace.json   — pipeline trace from examples/todo-trace.json
//   └── app/         — vite build of the harness-generated todo app
//
// Run after `npm run demo:todo` and `cd demo-output && npm install && npm run build`.
import { existsSync, mkdirSync, cpSync, copyFileSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const out = join(root, "gh-pages");
const appBuild = join(root, "demo-output", "build");
const trace = join(root, "examples", "todo-trace.json");

if (!existsSync(appBuild)) {
  console.error(`Missing ${appBuild}. Run \`npm run demo:todo\` then \`(cd demo-output && npm install && npm run build)\` first.`);
  process.exit(1);
}
if (!existsSync(trace)) {
  console.error(`Missing ${trace}. Run \`npm run demo:todo\` first.`);
  process.exit(1);
}

if (existsSync(out)) rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
cpSync(appBuild, join(out, "app"), { recursive: true });
copyFileSync(trace, join(out, "trace.json"));

const traceData = JSON.parse(readFileSync(trace, "utf8"));
const fixed = traceData.trace.filter((t) => t.via === "deterministic" && t.ok).length;
// LLM-driven count = subagent-finalised tasks + entity-schema seed (which has no `via`).
const llm =
  traceData.trace.filter((t) => t.via && t.via.startsWith("llm:") && t.ok).length + 1;
const totalTasks = fixed + llm;
const repairs = traceData.trace.filter((t) => t.ok === false).length;
const fileCount = (traceData.files || []).length;
const entity = traceData.entity?.entity || traceData.entity?.name || "Todo";

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>elegant/opencode — todo app harness demo</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body { margin: 0; font: 14px/1.5 system-ui, -apple-system, Segoe UI, sans-serif; }
  header { padding: 20px 24px; border-bottom: 1px solid #8884; background: #f8f8fa; }
  header.dark { background: #16181d; color: #eee; }
  @media (prefers-color-scheme: dark) { header { background: #16181d; color: #eee; } }
  h1 { font-size: 18px; margin: 0 0 4px; }
  p { margin: 0 0 6px; opacity: .8; font-size: 13px; }
  .stats { display: flex; gap: 16px; flex-wrap: wrap; font-size: 12px; opacity: .85; margin-top: 8px; }
  .stats span { padding: 2px 8px; border: 1px solid #8884; border-radius: 4px; }
  .links a { color: inherit; text-decoration: underline; margin-right: 12px; font-size: 12px; }
  iframe { width: 100%; height: calc(100vh - 130px); border: 0; display: block; }
</style>
</head>
<body>
<header>
  <h1>elegant/opencode — harness output</h1>
  <p>Live render of a ${fileCount}-file React + Redux <strong>${entity}</strong> app generated by the universal-architecture pipeline below.</p>
  <div class="stats">
    <span>${totalTasks} microtasks</span>
    <span>${fixed} deterministic</span>
    <span>${llm} LLM-driven</span>
    <span>${repairs} repair attempts</span>
    <span>${fileCount} files emitted</span>
  </div>
  <div class="links" style="margin-top: 8px;">
    <a href="https://github.com/grvpanchal/elegant-opencode">repo</a>
    <a href="trace.json">trace.json</a>
    <a href="app/">open app standalone</a>
  </div>
</header>
<iframe src="app/" title="harness-generated todo app"></iframe>
</body>
</html>
`;

writeFileSync(join(out, "index.html"), html, "utf8");
console.log(`Wrote ${out}/index.html, ${out}/trace.json, and ${out}/app/`);
